// <auto-generated />
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    partial class AnimalShelterAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterAPI.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Breed = "Domestic Loghair",
                            Gender = "Female",
                            Name = "Carlo",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 5,
                            Breed = "Pitbull",
                            Gender = "Female",
                            Name = "Pepper",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Breed = "Domestic Shorthair",
                            Gender = "Female",
                            Name = "Ivy",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Breed = "Chihuahua",
                            Gender = "Male",
                            Name = "Harry",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 0,
                            Breed = "Pitbull",
                            Gender = "Male",
                            Name = "Oreo",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Breed = "Domestic Longhair",
                            Gender = "Female",
                            Name = "Henry",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 3,
                            Breed = "Main Coon",
                            Gender = "Female",
                            Name = "Finny",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 4,
                            Breed = "Domestic Longhair",
                            Gender = "Female",
                            Name = "Salt",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 2,
                            Breed = "German Shepherd",
                            Gender = "Male",
                            Name = "Hachi",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 9,
                            Breed = "Domestic Shorthair",
                            Gender = "Male",
                            Name = "Charlie",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
